### ISSUE TITLE
BDA: add max-time option

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/xova#15]
Similar to ``--min-channels``, we also need a ``--max-time`` option, specifying the maximum time bin to employ (in seconds).

(if the data is not yet selfcal'ed, it may help to restrict the averaging to not exceed the expected cadence of the gain solutions...)

**Comment by sjperkins** [comment]
Should be trivial to re-use the same functionality from the normal averaging code.

**Comment by sjperkins** [comment]
Wait, not so trivial, the change also needs to go into the codex bda functionality.

**Comment by sjperkins** [comment]
Implemented in https://github.com/ska-sa/codex-africanus/pull/173/commits/64ee29480e00cb5db232532c6b8bc331b27454a1 and
https://github.com/ska-sa/xova/pull/12/commits/f2f1ffe794e68e11cda21dea752caf1aab3ea1c4
