### ISSUE TITLE
Hanning smoothing [feature request]

### ISSUE THREAD

**Issue by IanHeywood** [ska-sa/xova#23]
CASA's `hanningsmooth` task changes the visibilities but does not adjust the `SPECTRAL_WINDOW` table in the MS to reflect the fact that the number of channels in the MS has halved. This causes trouble for some applications, e.g. https://github.com/ratt-ru/shadeMS/issues/85

Adding a Hanning smoothing funtion to xova might represent the path of minimum misery for getting around this issue.

**Comment by IanHeywood** [comment]
Cross posting this from the shadems issue:

Actually `hanningsmooth` might not be the culprit. The parent MS has a mixture of X-band and P-band in the SPW table (X-band being a pointing scan I guess). The X-band SPWs (0-15) all have 64 channels, the P-band SPWs have 128...

**Comment by bennahugo** [comment]
You are right about the spw. Hanning smoothing essentially coarsens the
channel resolution by a factor of 2. If CASA spw tables do not reflect this
then it is a bug in casa

Not sure about the different sized spws for this. Never tested it myself -
I think Simon does a varcol read but we need to check

**Comment by IanHeywood** [comment]
I might owe `hanningsmooth` an apology: https://github.com/ratt-ru/shadeMS/issues/85

**Comment by sjperkins** [comment]
I think this is issue is resolved. Please feel free to open if it remains a problem.
