### ISSUE TITLE
SPW averaging failing

### ISSUE THREAD

**Issue by Mulan-94** [ska-sa/xova#3]
Hi @sjperkins SPW averaging fails with:
```
*** IndexError: tuple index out of range
```
at:
https://github.com/ska-sa/xova/blob/9d7ab8c9ecdef3bd2fc550d6ee065ba739fd7e7e/xova/apps/xova/averaging.py#L207

It seems to be because of the selection of item at index 0 in:
https://github.com/ska-sa/xova/blob/9d7ab8c9ecdef3bd2fc550d6ee065ba739fd7e7e/xova/apps/xova/averaging.py#L200
and subsequent lines. Without this selection, it appears to work fine.

On `Python 3.6`

**Comment by sjperkins** [comment]
@Mulan-94 I can't reproduce this with the latest dask-ms. Perhaps try an upgrade of dask-ms?

I did pick up that the number of channels in the output SPW was not been correctly set. I've fixed this in https://github.com/ska-sa/xova/pull/4.

**Comment by Mulan-94** [comment]
@sjperkins ok, let me upgrade and see

**Comment by Mulan-94** [comment]
I seem to be getting the same error. The `dask-ms` I'm using is the one from pypi and is version `0.2.2`

**Comment by sjperkins** [comment]
Hmmm I've upgraded to dask-ms 0.2.2 in https://github.com/ska-sa/xova/pull/5 but I still can't reproduce this on a local MS with multiple SPW's.

Does your MS have any rows in it's SPECTRAL_WINDOW table?

**Comment by Mulan-94** [comment]
> Does your MS have any rows in it's SPECTRAL_WINDOW table?

yeah, it has one row

**Comment by sjperkins** [comment]
What are the contents of the DATA_DESCRIPTION subtable?

Particularly the SPECTRAL_WINDOW_ID

**Comment by Mulan-94** [comment]
Here is the output:
![image](https://user-images.githubusercontent.com/12611059/69342382-1833a980-0c74-11ea-85e9-92ff7785b42d.png)
should I point you to the MS as well? Maybe you can try it out on your end also

**Comment by sjperkins** [comment]
Yes, let me know where its?

**Comment by Mulan-94** [comment]
on stills /home/andati/measurement_sets/1491291289.1ghz.1.1ghz.4hrs.ms

**Comment by sjperkins** [comment]
I ran xova master branch on my local copy of that MS.

It does log many dask-ms exceptions when dask-ms tries to inspect the shape of FLAG_CATEGORY, WEIGHT_SPECTRUM and SIGMA_SPECTRUM columns, as they are variably  shaped but don't contain data. This is harmless but annoying.

However, it does manage to average the MS.

Perhaps a reinstall of xova master branch would help?

**Comment by Mulan-94** [comment]
I did that but still no luck. Let me try with a different MS and see

**Comment by sjperkins** [comment]
I'll copy the MS from stills and try too.

**Comment by sjperkins** [comment]
> I'll copy the MS from stills and try too.

This worked for me!

**Comment by Mulan-94** [comment]
> This worked for me!

Ok, I found the culprit, I was using xarrayms instead of daskms. Thanks so much @sjperkins

**Comment by sjperkins** [comment]
> Ok, I found the culprit, I was using xarrayms instead of daskms.

How did you manage that? xova doesn't use xarrayms?

**Comment by Mulan-94** [comment]
What happened was in my script I had a **try** and **except** to import `xarray-ms` or `daskm-ms` and I never changed it.
